import Link from "next/link";
import {ArrowLeft,ArrowRight,BadgeCheck,BriefcaseBusiness,Clock3,MapPin,ShieldCheck,UsersRound} from "lucide-react";
import {formatRand,getPublicMarketData,healthLabel} from "@/lib/market-data";

export const revalidate=60;

export default async function PublicMarketPage(){
 const {cells,products,source,error}=await getPublicMarketData();
 const cell=cells[0];
 const reviewed=cell?.last_reviewed_at?new Intl.DateTimeFormat("en-ZA",{dateStyle:"medium",timeStyle:"short",timeZone:"Africa/Johannesburg"}).format(new Date(cell.last_reviewed_at)):"during pilot operations";
 return <main className="min-h-screen bg-[#f3efe6] px-4 py-5 text-[#12211a] md:px-8 md:py-8">
  <div className="mx-auto max-w-6xl">
   <div className="flex flex-wrap items-center justify-between gap-3"><Link href="/" className="inline-flex items-center gap-2 text-sm font-bold"><ArrowLeft size={16}/>Back to Nala</Link><span className="rounded-full bg-white px-3 py-2 text-xs font-extrabold shadow-sm">Public preview · no sign-in required</span></div>
   <header className="mt-7 rounded-[30px] bg-[#0d2b20] p-6 text-white md:p-10"><p className="text-xs font-black tracking-[.18em] text-[#dff09f]">CONTROLLED MARKET CELL</p><h1 className="mt-3 max-w-4xl font-serif text-4xl leading-tight md:text-6xl">See what Nala is preparing before you create an account.</h1><p className="mt-4 max-w-3xl text-sm leading-7 text-white/70 md:text-base">Nala grows task supply before worker acquisition. This page shows approved task products, pilot geography and current capacity without pretending paid work is always available.</p></header>

   <section className="mt-5 grid gap-4 md:grid-cols-3">
    <article className="rounded-3xl border border-black/10 bg-white p-5"><MapPin className="text-[#1d513b]"/><p className="mt-3 text-xs font-black tracking-[.12em] text-[#9a4d31]">PILOT AREA</p><strong className="mt-2 block text-xl">{cell?.geography||"Gauteng"}</strong><p className="mt-2 text-sm text-black/55">{cell?.verticals?.map(item=>item.replaceAll("_"," ")).join(" · ")||"Salons and beauty · Trades and repairs"}</p></article>
    <article className="rounded-3xl border border-black/10 bg-white p-5"><BriefcaseBusiness className="text-[#1d513b]"/><p className="mt-3 text-xs font-black tracking-[.12em] text-[#9a4d31]">TASK SUPPLY</p><strong className="mt-2 block text-xl">{cell?healthLabel(cell.health_band):"Building task supply"}</strong><p className="mt-2 text-sm text-black/55">{cell?.funded_open_task_count||0} funded open tasks · reviewed <span className="tabular-nums">{reviewed}</span></p></article>
    <article className="rounded-3xl border border-black/10 bg-white p-5"><UsersRound className="text-[#1d513b]"/><p className="mt-3 text-xs font-black tracking-[.12em] text-[#9a4d31]">CAPACITY CONTROL</p><strong className="mt-2 block text-xl">{cell?.active_worker_count||0} / {cell?.worker_capacity||100} active workers</strong><p className="mt-2 text-sm text-black/55">Worker intake can pause when demand is thin. Registrations are not treated as success.</p></article>
   </section>

   <section className="mt-8"><div className="flex flex-wrap items-end justify-between gap-3"><div><p className="text-xs font-black tracking-[.14em] text-[#9a4d31]">APPROVED OUTCOME PRODUCTS</p><h2 className="mt-2 font-serif text-4xl">Clear work, packaged before publishing.</h2></div><span className="text-xs text-black/45">Data source: {source}{error?" · live connection unavailable":""}</span></div>
    <div className="mt-5 grid gap-4 md:grid-cols-2">{products.length?products.map(product=><article key={product.id} className="rounded-[26px] border border-black/10 bg-[#fffdf8] p-6"><div className="flex items-start justify-between gap-4"><div><span className="rounded-full bg-[#dff09f] px-3 py-1 text-[10px] font-black uppercase tracking-[.12em]">{product.status}</span><h3 className="mt-4 text-2xl font-black">{product.title}</h3><p className="mt-2 text-sm font-bold text-[#1d513b]">{product.category}</p></div><div className="text-right"><small className="block text-[10px] font-black text-black/45">MINIMUM WORKER PAY</small><strong className="mt-1 block text-2xl">{formatRand(product.minimum_worker_pay_cents)}</strong></div></div><p className="mt-4 text-sm leading-6 text-black/60">{product.outcome}</p><div className="mt-5 flex flex-wrap gap-2 text-xs font-bold"><span className="inline-flex items-center gap-1 rounded-full bg-[#f0eadc] px-3 py-2"><Clock3 size={14}/>{product.expected_active_minutes} min + {product.expected_revision_minutes} min review allowance</span><span className="inline-flex items-center gap-1 rounded-full bg-[#f0eadc] px-3 py-2"><BadgeCheck size={14}/>{product.revision_limit} revision limit</span><span className="inline-flex items-center gap-1 rounded-full bg-[#f0eadc] px-3 py-2"><ShieldCheck size={14}/>{product.remote_capable?"Remote capable":"Controlled on-site"}</span></div></article>):<article className="col-span-full rounded-[26px] border border-black/10 bg-white p-8"><h3 className="text-xl font-black">Task products are temporarily unavailable.</h3><p className="mt-2 text-sm text-black/55">Nala will not manufacture fake task supply. The catalogue will reappear when the live source is available.</p></article>}</div>
   </section>

   <section className="mt-8 rounded-[28px] bg-[#fff6df] p-6 md:p-8"><p className="text-xs font-black tracking-[.14em] text-[#9a4d31]">NO FORCED SIGN-IN</p><h2 className="mt-2 text-3xl font-black">Explore first. Join only when a real action requires an account.</h2><p className="mt-3 max-w-3xl text-sm leading-6 text-black/60">Workers can inspect categories, payment floors, readiness expectations and capacity status publicly. Businesses can understand the outcome catalogue before starting structured intake.</p><div className="mt-5 flex flex-wrap gap-3"><Link href="/worker" className="inline-flex items-center gap-2 rounded-full bg-[#12211a] px-5 py-3 text-sm font-black text-white">Explore worker journey <ArrowRight size={16}/></Link><Link href="/business" className="inline-flex items-center gap-2 rounded-full bg-white px-5 py-3 text-sm font-black">Explore business workspace <ArrowRight size={16}/></Link><Link href="/auth" className="inline-flex items-center gap-2 rounded-full border border-black/10 bg-white px-5 py-3 text-sm font-black">Join or sign in <ArrowRight size={16}/></Link></div></section>
  </div>
 </main>;
}
