import Link from "next/link";
import {ArrowRight,BadgeCheck,BriefcaseBusiness,Building2,Check,CircleDollarSign,Clock3,ShieldCheck,Sparkles,Star} from "lucide-react";

const tasks=[
 {category:"Customer support",title:"Confirm tomorrow’s salon appointments",business:"Lerato Beauty Studio",pay:"R100",time:"45–60 min",proof:"Customer communication",detail:"Contact 10 customers, record every reply and flag anything the owner must handle."},
 {category:"Sales administration",title:"Follow up on six open quotations",business:"Mandla Electrical",pay:"R150",time:"60–90 min",proof:"Professional writing",detail:"Prepare helpful follow-ups without inventing urgency, discounts or promises."},
 {category:"Data administration",title:"Clean a customer contact spreadsheet",business:"Mpho Catering",pay:"R120",time:"60 min",proof:"Data accuracy",detail:"Standardise contact details, flag possible duplicates and return a clear change log."}
];
const steps=[
 ["01","Tell us what you already do","A short, honest profile recognises practical and informal experience — not only formal employment."],
 ["02","See a suitable starting point","Nala shows work that matches your access, strengths and readiness rather than sending you into a crowded application queue."],
 ["03","Practise the specific work","Complete a job-specific readiness mission with realistic decisions, written work, feedback and a meaningful pass standard."],
 ["04","Accept clear, paid work","See payment, time, scope, device needs and expected evidence before you commit."],
 ["05","Do the work with guidance","Use a structured workbench, quality checks and clear escalation rules while completing the real task."],
 ["06","Turn the result into proof","The business verifies the work. Your readiness, quality and reliability become portable evidence in your Work Passport."]
];
const simulations=[
 {tag:"Customer support",title:"Appointment confirmation shift",copy:"Inspect booking conflicts, write a real confirmation message, classify replies and prepare a shift handover.",demo:["Spot a double-booking","Handle a late arrival","Log every customer outcome"]},
 {tag:"Data administration",title:"Customer data cleanup lab",copy:"Find record errors, choose safe cleanup actions, preserve the original file and produce a proper change log.",demo:["Identify invalid fields","Flag possible duplicates","Explain unresolved exceptions"]},
 {tag:"Finance administration",title:"Invoice reminder control room",copy:"Verify invoice facts, separate disputes from reminders and prepare accurate, respectful customer communication.",demo:["Audit before contact","Classify customer replies","Escalate a dispute safely"]}
];

export default function Home(){return <div className="landing-v2">
 <header className="v2-nav"><div className="v2-wrap v2-nav-inner"><Link href="/" className="v2-brand">nala<span>.</span></Link><nav className="v2-links" aria-label="Primary navigation"><a href="#work">Real work</a><a href="#journey">How it works</a><a href="#practice">Practice</a><a href="#business">For businesses</a><Link href="/worker" className="v2-nav-cta">Open Nala <ArrowRight size={15}/></Link></nav></div></header>
 <main>
  <section className="v2-hero"><div className="v2-wrap v2-hero-grid"><div><div className="v2-kicker">Built for the first real opportunity</div><h1>Earn your <em>first income.</em><br/>Build experience people can verify.</h1><p className="v2-hero-lede">Nala prepares young people for real starter tasks, guides the work from start to finish, and turns every approved result into proof they can carry forward.</p><div className="v2-actions"><Link href="/worker" className="v2-primary">Start building experience <ArrowRight size={18}/></Link><Link href="/business" className="v2-secondary">I run a business <Building2 size={17}/></Link></div><div className="v2-manifesto">Experience should not be the thing that keeps you from getting experience.</div></div>
   <div className="v2-journey" aria-label="Sample Nala work journey"><div className="v2-person"><div className="v2-avatar">TM</div><div><strong>Thandi Mokoena</strong><p>22 · Matric · Strong with people</p></div><div className="v2-score"><Star size={13} fill="currentColor"/> 96%</div></div><div className="v2-task"><div className="v2-task-top"><div><small>Current starter task</small><h3>Confirm 10 salon appointments</h3><p>Lerato Beauty Studio · Remote</p></div><div className="v2-pay"><small>You earn</small><strong>R100</strong><span>45–60 min</span></div></div><div className="v2-progress"><span/><span/><span/><span/></div><div className="v2-proof"><div><span className="v2-micro">Readiness</span><strong>Simulation passed · 88%</strong></div><div><span className="v2-micro">This task proves</span><strong>Customer communication</strong></div></div></div></div>
  </div></section>

  <section className="v2-section" id="work"><div className="v2-wrap"><div className="v2-section-head"><div><div className="v2-kicker">Real starter work</div><h2 className="v2-section-title">Not another application queue. Work you can prepare for and complete.</h2></div><p className="v2-section-copy">Every task shows what it pays, how long it should take, what is expected and what evidence it can add to your work history.</p></div><div className="v2-task-grid">{tasks.map(task=><article className="v2-market-card" key={task.title}><div className="v2-market-top"><span className="v2-pill">{task.category}</span><strong>{task.pay}</strong></div><h3>{task.title}</h3><p><strong>{task.business}</strong></p><p>{task.detail}</p><div className="v2-meta"><span><Clock3 size={13}/> {task.time}</span><span><CircleDollarSign size={13}/> Payment shown</span></div><div className="v2-unlock"><Sparkles size={14}/> Readiness mission · {task.proof}</div></article>)}</div></div></section>

  <section className="v2-section" id="journey"><div className="v2-wrap v2-story"><div><div className="v2-kicker">A complete first-work journey</div><h2>From what you already know to proof that speaks for you.</h2><p className="v2-story-intro">Nala does not ask a young person to pretend they already have a career. It creates a safe starting point and records what they prove along the way.</p></div><div className="v2-timeline">{steps.map(([n,title,copy])=><article className="v2-step" key={n}><span className="v2-step-num">{n}</span><div><h3>{title}</h3><p>{copy}</p></div></article>)}</div></div></section>

  <section className="v2-section" id="practice"><div className="v2-wrap"><div className="v2-section-head"><div><div className="v2-kicker">Practise before real work</div><h2 className="v2-section-title">Train for the actual task — not a generic quiz.</h2></div><p className="v2-section-copy">Each work category has its own readiness mission, interaction types, coaching and pass standard. A worker must demonstrate understanding before task acceptance.</p></div><div className="v2-sim-grid">{simulations.map(sim=><article className="v2-sim-card" key={sim.title}><span className="v2-pill">{sim.tag}</span><h3>{sim.title}</h3><p>{sim.copy}</p><div className="v2-sim-demo"><strong>Inside this mission</strong>{sim.demo.map(item=><div className="v2-demo-row" key={item}><span className="v2-demo-dot"/>{item}</div>)}</div></article>)}</div><div className="v2-actions" style={{justifyContent:"center",marginTop:48}}><Link href="/worker" className="v2-secondary">Explore the practice library <ArrowRight size={17}/></Link></div></div></section>

  <section className="v2-section"><div className="v2-wrap v2-passport"><div><div className="v2-kicker">Proof-of-Work Passport</div><h2>Do not just say you are reliable. Show what businesses verified.</h2><p className="v2-passport-copy">Every approved task and passed readiness mission becomes structured evidence: the work completed, skills demonstrated, business verification and reliability over time.</p><div className="v2-actions"><Link href="/passport" className="v2-primary">View the sample Passport <ArrowRight size={17}/></Link></div></div><div className="v2-passport-card"><div className="v2-passport-head"><div className="v2-avatar">TM</div><div><h3>Thandi Mokoena</h3><p>Proof-of-Work Passport</p></div><BadgeCheck size={28} color="#155d48" style={{marginLeft:"auto"}}/></div><div className="v2-passport-stats"><div><strong>3</strong><span>Verified tasks</span></div><div><strong>96%</strong><span>Reliability</span></div><div><strong>4</strong><span>Skills proven</span></div></div><div className="v2-evidence"><div><span>Appointment confirmation</span><strong>Verified · 5/5</strong></div><div><span>Customer data cleanup</span><strong>Verified · 5/5</strong></div><div><span>Readiness missions</span><strong>3 passed</strong></div></div></div></div></section>

  <section className="v2-section v2-business" id="business"><div className="v2-wrap v2-business-grid"><div><div className="v2-kicker" style={{color:"#f6c56d"}}>For small businesses</div><h2>Get the important small work done — without hiring for a full-time role.</h2><p>Choose an outcome, add your business information and review the final result. Nala prepares the worker, structures the task and keeps scope, quality checks and evidence visible.</p><div className="v2-actions"><Link href="/business" className="v2-primary">Open the business workspace <ArrowRight size={17}/></Link></div></div><div className="v2-template-stack">{["Confirm tomorrow’s appointments","Prepare quotation follow-ups","Clean customer spreadsheets","Prepare invoice reminders","Draft review-ready social content"].map((item,index)=><div className="v2-template" key={item}><div><span>0{index+1} · Structured task template</span><strong>{item}</strong></div><BriefcaseBusiness size={20}/></div>)}</div></div></section>

  <section className="v2-section"><div className="v2-wrap v2-safety"><div><div className="v2-kicker">Trust must be built into the work</div><h2 className="v2-section-title">Starter work should never mean careless or exploitative work.</h2></div><div className="v2-safety-list">{["Payment, time and expected evidence are visible before acceptance.","Job-specific readiness is completed before supported tasks can be accepted.","Workers are guided by approved instructions and clear authority boundaries.","Businesses can verify completed work or request a documented correction.","Readiness results and approved work are recorded separately and transparently.","Demo records stay isolated from future live marketplace data."].map(item=><div className="v2-safety-item" key={item}><ShieldCheck size={18} color="#155d48"/><span>{item}</span></div>)}</div></div></section>

  <section className="v2-final"><div className="v2-wrap"><div className="v2-final-box"><h2>Nobody should be locked out of work because they have never worked.</h2><p>Nala gives a young person the first safe chance, records what they prove and helps that first task lead somewhere.</p><div className="v2-actions"><Link href="/worker" className="v2-primary">Start building experience <ArrowRight size={18}/></Link><Link href="/business" className="v2-secondary" style={{color:"white",borderColor:"rgba(255,255,255,.38)"}}>Create a task <Building2 size={17}/></Link></div></div></div></section>
 </main>
 <footer className="v2-footer"><div className="v2-wrap v2-footer-inner"><div><strong className="v2-brand">nala<span>.</span></strong><p>Real work. Real proof. Real progress.</p></div><div className="v2-footer-links"><a href="#work">Real work</a><a href="#journey">How it works</a><a href="#practice">Practice</a><a href="#business">For businesses</a></div><div>Built in South Africa · © 2026 Nala</div></div></footer>
 </div>