"use client";

import {useEffect,useMemo,useState} from "react";
import Link from "next/link";
import {BadgeCheck,BriefcaseBusiness,Building2,Check,ChevronRight,CircleDollarSign,ClipboardCheck,Clock3,FileCheck2,Home,LayoutDashboard,LogOut,Menu,Plus,ShieldCheck,Sparkles,Star,UserRound,X} from "lucide-react";

type Role="worker"|"business"|"admin";
type View="dashboard"|"tasks"|"task"|"workbench"|"passport"|"create"|"reviews"|"admin";
type TaskStatus="open"|"accepted"|"submitted"|"verified";
type Task={id:string;title:string;business:string;category:string;pay:number;duration:string;description:string;skills:string[];status:TaskStatus;worker?:string;progress?:number;submission?:string;rating?:number};
type State={role:Role;workerName:string;businessName:string;tasks:Task[];earnings:number;verified:number;reliability:number};

const seed:State={role:"worker",workerName:"Thandi Mokoena",businessName:"Lerato Beauty Studio",earnings:350,verified:4,reliability:96,tasks:[
{id:"appointment-confirmation",title:"Confirm tomorrow's appointments",business:"Lerato Beauty Studio",category:"Customer support",pay:100,duration:"45–60 min",description:"Contact 10 customers using the approved message, record their responses and flag anything the owner must handle.",skills:["Customer communication","Accuracy","WhatsApp admin"],status:"open"},
{id:"quote-follow-up",title:"Prepare quote follow-up messages",business:"Mandla Electrical",category:"Sales administration",pay:150,duration:"60–90 min",description:"Prepare professional follow-up messages for eight customers who received quotations this month.",skills:["Professional writing","Sales support","Attention to detail"],status:"open"},
{id:"content-pack",title:"Create five social post drafts",business:"Kasi Kitchen",category:"Digital marketing",pay:220,duration:"2 hours",description:"Turn a supplied menu and promotion into five clear social-media post drafts.",skills:["Content writing","Digital marketing","Brand tone"],status:"open"},
{id:"completed-1",title:"Clean customer contact spreadsheet",business:"Naledi Repairs",category:"Data administration",pay:120,duration:"1 hour",description:"Standardise phone numbers and remove duplicates.",skills:["Spreadsheet cleanup","Data accuracy"],status:"verified",worker:"Thandi Mokoena",progress:100,rating:5}
]};

const steps=["Review the approved customer list","Use the approved confirmation message","Record confirmed, cancelled or no-response outcomes","Flag questions for the business owner","Complete the final quality check"];

function useNalaState(){
 const [data,setData]=useState<State>(seed); const [ready,setReady]=useState(false);
 useEffect(()=>{try{const stored=localStorage.getItem("nala-production-demo");if(stored)setData(JSON.parse(stored));}catch{}setReady(true)},[]);
 useEffect(()=>{if(ready)localStorage.setItem("nala-production-demo",JSON.stringify(data))},[data,ready]);
 return {data,setData,ready};
}

function Pill({children}:{children:React.ReactNode}){return <span className="inline-flex rounded-full bg-leaf/35 px-3 py-1 text-xs font-bold text-forest">{children}</span>}
function Metric({icon:Icon,label,value}:{icon:any;label:string;value:string}){return <div className="rounded-3xl border border-black/5 bg-white p-5 shadow-sm"><Icon size={21} className="text-forest"/><p className="mt-4 text-3xl font-black tracking-tight">{value}</p><p className="mt-1 text-sm text-black/55">{label}</p></div>}
function Empty({title,body}:{title:string;body:string}){return <div className="rounded-[2rem] border border-dashed border-black/15 bg-white/60 p-10 text-center"><Sparkles className="mx-auto text-forest"/><h3 className="mt-4 text-xl font-black">{title}</h3><p className="mx-auto mt-2 max-w-md text-sm leading-6 text-black/55">{body}</p></div>}

export function NalaApp({initialView="dashboard"}:{initialView?:View}){
 const {data,setData,ready}=useNalaState(); const [view,setView]=useState<View>(initialView); const [selected,setSelected]=useState(data.tasks[0]?.id||""); const [mobile,setMobile]=useState(false); const [practice,setPractice]=useState(false); const [checks,setChecks]=useState<number[]>([]); const [submission,setSubmission]=useState("");
 const task=data.tasks.find(t=>t.id===selected)||data.tasks[0];
 const accepted=data.tasks.filter(t=>t.status==="accepted"||t.status==="submitted");
 const open=data.tasks.filter(t=>t.status==="open");
 const verified=data.tasks.filter(t=>t.status==="verified");
 const nav=data.role==="worker"?[['dashboard','Home',Home],['tasks','Find work',BriefcaseBusiness],['workbench','My work',ClipboardCheck],['passport','Work passport',BadgeCheck]]:data.role==="business"?[['dashboard','Overview',LayoutDashboard],['create','Create task',Plus],['tasks','Tasks',BriefcaseBusiness],['reviews','Reviews',FileCheck2]]:[['admin','Operations',ShieldCheck],['tasks','All tasks',BriefcaseBusiness]];
 function chooseRole(role:Role){setData(d=>({...d,role}));setView(role==="admin"?"admin":"dashboard")}
 function acceptTask(){setPractice(true)}
 function passPractice(){setData(d=>({...d,tasks:d.tasks.map(t=>t.id===task.id?{...t,status:"accepted",worker:d.workerName,progress:0}:t)}));setPractice(false);setView("workbench")}
 function completeStep(i:number){setChecks(c=>c.includes(i)?c.filter(x=>x!==i):[...c,i])}
 function submitWork(){if(!task||checks.length<steps.length||!submission.trim())return;setData(d=>({...d,tasks:d.tasks.map(t=>t.id===task.id?{...t,status:"submitted",progress:100,submission}:t)}));setSubmission("");setView("dashboard")}
 function verifyTask(id:string){const target=data.tasks.find(t=>t.id===id);if(!target)return;setData(d=>({...d,earnings:d.earnings+target.pay,verified:d.verified+1,reliability:Math.min(100,d.reliability+1),tasks:d.tasks.map(t=>t.id===id?{...t,status:"verified",rating:5}:t)}))}
 function createTask(e:React.FormEvent<HTMLFormElement>){e.preventDefault();const f=new FormData(e.currentTarget);const id=`task-${Date.now()}`;const next:Task={id,title:String(f.get("title")),business:data.businessName,category:String(f.get("category")),pay:Number(f.get("pay")),duration:String(f.get("duration")),description:String(f.get("description")),skills:String(f.get("skills")).split(',').map(s=>s.trim()).filter(Boolean),status:"open"};setData(d=>({...d,tasks:[next,...d.tasks]}));e.currentTarget.reset();setSelected(id);setView("task")}
 if(!ready)return <main className="grid min-h-screen place-items-center"><div className="text-center"><div className="mx-auto h-10 w-10 animate-spin rounded-full border-4 border-leaf border-t-forest"/><p className="mt-4 font-bold">Opening Nala…</p></div></main>;
 return <div className="min-h-screen bg-sand">
  <header className="sticky top-0 z-30 border-b border-black/5 bg-sand/90 backdrop-blur"><div className="mx-auto flex h-16 max-w-[1500px] items-center justify-between px-4 sm:px-6"><Link href="/" className="text-2xl font-black tracking-[-.04em]">nala<span className="text-forest">.</span></Link><div className="flex items-center gap-3"><div className="hidden text-right sm:block"><p className="text-sm font-black">{data.role==="worker"?data.workerName:data.role==="business"?data.businessName:"Nala operations"}</p><p className="text-xs capitalize text-black/45">{data.role} workspace</p></div><button onClick={()=>setMobile(!mobile)} className="rounded-xl border border-black/10 bg-white p-2 lg:hidden">{mobile?<X/>:<Menu/>}</button><button onClick={()=>{localStorage.removeItem("nala-production-demo");setData(seed);setView("dashboard")}} className="hidden rounded-xl border border-black/10 bg-white p-2 text-black/55 sm:block" title="Reset demo"><LogOut size={18}/></button></div></div></header>
  <div className="mx-auto grid max-w-[1500px] lg:grid-cols-[250px_1fr]">
   <aside className={`${mobile?'block':'hidden'} border-r border-black/5 bg-white/55 p-4 lg:block lg:min-h-[calc(100vh-4rem)]`}><div className="mb-5 rounded-2xl bg-ink p-4 text-white"><p className="text-xs font-bold uppercase tracking-widest text-leaf">Demo role</p><div className="mt-3 grid grid-cols-3 gap-1">{(['worker','business','admin'] as Role[]).map(r=><button key={r} onClick={()=>chooseRole(r)} className={`rounded-xl px-2 py-2 text-xs font-bold capitalize ${data.role===r?'bg-sun text-ink':'bg-white/10'}`}>{r}</button>)}</div></div><nav className="space-y-1">{nav.map(([id,label,Icon]:any)=><button key={id} onClick={()=>{setView(id);setMobile(false)}} className={`flex w-full items-center gap-3 rounded-2xl px-4 py-3 text-left text-sm font-bold ${view===id?'bg-forest text-white':'hover:bg-white'}`}><Icon size={19}/>{label}</button>)}</nav><div className="mt-8 rounded-2xl bg-leaf/30 p-4"><p className="text-sm font-black">Safe work first</p><p className="mt-2 text-xs leading-5 text-black/55">Every Nala task displays scope, payment and evidence requirements before acceptance.</p></div></aside>
   <main className="min-w-0 p-4 sm:p-6 lg:p-10">
    {view==="dashboard"&&<section><div className="flex flex-col justify-between gap-4 sm:flex-row sm:items-end"><div><Pill>{data.role==="worker"?'Your next step':data.role==="business"?'Business workspace':'Operations'}</Pill><h1 className="mt-4 text-4xl font-black tracking-[-.04em] sm:text-5xl">{data.role==="worker"?`Welcome back, ${data.workerName.split(' ')[0]}.`:data.role==="business"?'Get important work moving.':'Protect the Nala marketplace.'}</h1><p className="mt-3 max-w-2xl text-black/55">{data.role==="worker"?'Build verified experience one paid task at a time.':data.role==="business"?'Create structured tasks, support new talent and review completed work.':'Review task quality, disputes and marketplace safety.'}</p></div><button onClick={()=>setView(data.role==="business"?'create':data.role==="worker"?'tasks':'admin')} className="rounded-2xl bg-ink px-5 py-3 font-bold text-white">{data.role==="business"?'Create a task':data.role==="worker"?'Find starter work':'Open queue'}</button></div>
     <div className="mt-8 grid gap-4 sm:grid-cols-3"><Metric icon={CircleDollarSign} label={data.role==="worker"?'Total earnings':'Task value created'} value={`R${data.role==="worker"?data.earnings:data.tasks.reduce((s,t)=>s+t.pay,0)}`}/><Metric icon={BadgeCheck} label={data.role==="worker"?'Verified tasks':'Verified outcomes'} value={String(data.verified)}/><Metric icon={Star} label={data.role==="worker"?'Reliability score':'Average worker quality'} value={`${data.reliability}%`}/></div>
     <div className="mt-8 grid gap-6 xl:grid-cols-[1.3fr_.7fr]"><div className="rounded-[2rem] bg-white p-5 sm:p-7"><div className="flex items-center justify-between"><div><p className="text-sm font-bold text-forest">Current activity</p><h2 className="mt-1 text-2xl font-black">{data.role==="worker"?'Your accepted work':'Tasks needing attention'}</h2></div></div><div className="mt-5 space-y-3">{(data.role==="worker"?accepted:data.tasks.filter(t=>t.status==="submitted")).length?(data.role==="worker"?accepted:data.tasks.filter(t=>t.status==="submitted")).map(t=><button key={t.id} onClick={()=>{setSelected(t.id);setView(data.role==="worker"?'workbench':'reviews')}} className="flex w-full items-center justify-between rounded-2xl border border-black/5 p-4 text-left hover:border-forest/30"><div><p className="font-black">{t.title}</p><p className="mt-1 text-sm text-black/50">{t.business} · {t.status}</p></div><ChevronRight/></button>):<Empty title="Nothing waiting" body={data.role==="worker"?'Accept a starter task when you are ready.':'Submitted work will appear here for review.'}/>}</div></div><div className="rounded-[2rem] bg-forest p-6 text-white"><Sparkles className="text-leaf"/><h2 className="mt-5 text-2xl font-black">{data.role==="worker"?'Your next opportunity':'Why this matters'}</h2><p className="mt-3 leading-7 text-white/70">{data.role==="worker"?'Complete one more customer-support task to unlock the Reception & Front Desk pathway.':'Small, structured tasks save business time while creating verified first experience.'}</p><button onClick={()=>setView(data.role==="worker"?'tasks':'create')} className="mt-6 rounded-2xl bg-sun px-4 py-3 font-black text-ink">Continue <ChevronRight className="inline" size={18}/></button></div></div>
    </section>}
    {view==="tasks"&&<section><Pill>Transparent starter work</Pill><h1 className="mt-4 text-4xl font-black tracking-tight">{data.role==="business"?'Your task board':'Find work you can succeed at.'}</h1><p className="mt-3 text-black/55">Clear scope, payment, time and evidence—before anyone accepts.</p><div className="mt-8 grid gap-4 lg:grid-cols-2">{(data.role==="worker"?open:data.tasks).map(t=><button key={t.id} onClick={()=>{setSelected(t.id);setView("task")}} className="rounded-[1.7rem] border border-black/5 bg-white p-5 text-left shadow-sm transition hover:-translate-y-1 hover:shadow-lg"><div className="flex justify-between gap-4"><Pill>{t.category}</Pill><span className="text-2xl font-black">R{t.pay}</span></div><h2 className="mt-5 text-2xl font-black">{t.title}</h2><p className="mt-2 text-sm text-black/50">{t.business} · {t.duration}</p><p className="mt-4 line-clamp-2 leading-6 text-black/60">{t.description}</p><div className="mt-5 flex flex-wrap gap-2">{t.skills.map(s=><span key={s} className="rounded-full bg-sand px-3 py-1 text-xs font-bold">{s}</span>)}</div></button>)}</div></section>}
    {view==="task"&&task&&<section className="mx-auto max-w-4xl"><button onClick={()=>setView("tasks")} className="text-sm font-bold text-forest">← Back to tasks</button><div className="mt-5 rounded-[2.2rem] bg-white p-6 shadow-sm sm:p-10"><div className="flex flex-col justify-between gap-5 sm:flex-row"><div><Pill>{task.category}</Pill><h1 className="mt-4 text-4xl font-black tracking-tight">{task.title}</h1><p className="mt-3 text-black/50">{task.business}</p></div><div className="rounded-3xl bg-sand p-5 sm:min-w-44"><p className="text-sm text-black/45">You earn</p><p className="text-4xl font-black">R{task.pay}</p><p className="mt-1 text-sm text-black/50">{task.duration}</p></div></div><div className="mt-8 grid gap-6 md:grid-cols-2"><div><h2 className="text-xl font-black">What you will do</h2><p className="mt-3 leading-7 text-black/65">{task.description}</p><h2 className="mt-7 text-xl font-black">What this proves</h2><div className="mt-3 flex flex-wrap gap-2">{task.skills.map(s=><Pill key={s}>{s}</Pill>)}</div></div><div className="rounded-3xl bg-leaf/25 p-5"><ShieldCheck className="text-forest"/><h2 className="mt-4 text-xl font-black">Protected task</h2><ul className="mt-3 space-y-2 text-sm leading-6 text-black/60"><li>✓ Payment shown before acceptance</li><li>✓ No unpaid trial work</li><li>✓ Approved customer message only</li><li>✓ Business handles sensitive questions</li><li>✓ Work becomes verified experience</li></ul></div></div>{data.role==="worker"&&task.status==="open"&&<button onClick={acceptTask} className="mt-8 w-full rounded-2xl bg-ink px-6 py-4 font-black text-white">Start readiness check</button>}{data.role==="worker"&&task.status==="accepted"&&<button onClick={()=>setView("workbench")} className="mt-8 w-full rounded-2xl bg-forest px-6 py-4 font-black text-white">Open workbench</button>}</div>
     {practice&&<div className="fixed inset-0 z-50 grid place-items-center bg-ink/70 p-4"><div className="w-full max-w-xl rounded-[2rem] bg-white p-6 sm:p-8"><div className="flex justify-between"><Pill>Readiness simulation</Pill><button onClick={()=>setPractice(false)}><X/></button></div><h2 className="mt-5 text-3xl font-black">A customer asks to move their appointment.</h2><p className="mt-3 leading-7 text-black/60">What should you do?</p><div className="mt-5 space-y-3"><button className="w-full rounded-2xl border border-black/10 p-4 text-left">Change it without telling the owner</button><button onClick={passPractice} className="w-full rounded-2xl border-2 border-forest bg-leaf/25 p-4 text-left font-bold">Record the request and flag it for the owner ✓</button><button className="w-full rounded-2xl border border-black/10 p-4 text-left">Ignore the message</button></div><p className="mt-5 text-sm text-black/45">Choose the safe answer to accept this task.</p></div></div>}
    </section>}
    {view==="workbench"&&<section><Pill>Guided workbench</Pill><h1 className="mt-4 text-4xl font-black">Complete work with confidence.</h1><div className="mt-8 grid gap-6 xl:grid-cols-[1fr_.65fr]"><div className="rounded-[2rem] bg-white p-6"><h2 className="text-2xl font-black">{task?.title||'No active task'}</h2>{task&&task.status!=="open"?<><div className="mt-6 space-y-3">{steps.map((s,i)=><button key={s} onClick={()=>completeStep(i)} className={`flex w-full items-center gap-3 rounded-2xl border p-4 text-left ${checks.includes(i)?'border-forest bg-leaf/20':'border-black/10'}`}><span className={`grid h-7 w-7 shrink-0 place-items-center rounded-full ${checks.includes(i)?'bg-forest text-white':'bg-sand'}`}>{checks.includes(i)?<Check size={16}/>:i+1}</span><span className="font-bold">{s}</span></button>)}</div><label className="mt-6 block text-sm font-black">Completion summary</label><textarea value={submission} onChange={e=>setSubmission(e.target.value)} className="mt-2 min-h-32 w-full rounded-2xl border border-black/10 bg-sand p-4 outline-none focus:border-forest" placeholder="Example: 8 confirmed, 1 cancellation, 1 question flagged for the owner."/><button onClick={submitWork} disabled={checks.length<steps.length||!submission.trim()} className="mt-4 w-full rounded-2xl bg-ink px-5 py-4 font-black text-white disabled:cursor-not-allowed disabled:opacity-35">Submit for business verification</button></>:<Empty title="No accepted task" body="Choose a starter task and pass its readiness simulation first."/>}</div><div className="rounded-[2rem] bg-forest p-6 text-white"><Sparkles className="text-leaf"/><h2 className="mt-4 text-2xl font-black">Nala guide</h2><p className="mt-3 leading-7 text-white/70">Stay inside the approved scope. Never promise refunds, change appointments or share customer information outside this task.</p><div className="mt-6 rounded-2xl bg-white/10 p-4"><p className="text-sm font-bold text-leaf">Quality check</p><p className="mt-2 text-sm leading-6 text-white/70">Names match the supplied list, every outcome is recorded, and questions are flagged rather than answered.</p></div></div></div></section>}
    {view==="passport"&&<section><Pill>Portable proof of work</Pill><h1 className="mt-4 text-4xl font-black">{data.workerName}'s Work Passport</h1><p className="mt-3 text-black/55">Verified evidence, not empty claims.</p><div className="mt-8 grid gap-4 sm:grid-cols-3"><Metric icon={CircleDollarSign} label="Earned through Nala" value={`R${data.earnings}`}/><Metric icon={BadgeCheck} label="Verified tasks" value={String(data.verified)}/><Metric icon={Star} label="Reliability" value={`${data.reliability}%`}/></div><div className="mt-8 rounded-[2rem] bg-white p-6"><h2 className="text-2xl font-black">Verified experience</h2><div className="mt-5 space-y-4">{verified.map(t=><article key={t.id} className="rounded-3xl border border-black/5 p-5"><div className="flex items-start justify-between gap-4"><div><div className="flex items-center gap-2"><BadgeCheck className="text-forest" size={19}/><p className="font-black">{t.title}</p></div><p className="mt-1 text-sm text-black/50">Verified by {t.business}</p></div><span className="font-black">{t.rating||5}/5</span></div><p className="mt-4 text-sm leading-6 text-black/60">{t.description}</p><div className="mt-4 flex flex-wrap gap-2">{t.skills.map(s=><Pill key={s}>{s}</Pill>)}</div></article>)}</div></div></section>}
    {view==="create"&&<section className="mx-auto max-w-3xl"><Pill>Structured business outcome</Pill><h1 className="mt-4 text-4xl font-black">Create a safe paid task.</h1><p className="mt-3 text-black/55">Nala makes scope, payment and expected evidence clear before publishing.</p><form onSubmit={createTask} className="mt-8 space-y-5 rounded-[2rem] bg-white p-6 sm:p-8">{[['title','Task title','Confirm tomorrow’s appointments'],['category','Category','Customer support'],['duration','Expected time','45–60 min'],['pay','Payment in rand','100'],['skills','Skills, comma separated','Customer communication, Accuracy']].map(([name,label,placeholder])=><label key={name} className="block"><span className="text-sm font-black">{label}</span><input required name={name} type={name==='pay'?'number':'text'} placeholder={placeholder} className="mt-2 w-full rounded-2xl border border-black/10 bg-sand px-4 py-3 outline-none focus:border-forest"/></label>)}<label className="block"><span className="text-sm font-black">Clear instructions</span><textarea required name="description" className="mt-2 min-h-32 w-full rounded-2xl border border-black/10 bg-sand p-4 outline-none focus:border-forest" placeholder="Describe exactly what the worker must do and what must be submitted."/></label><div className="rounded-2xl bg-leaf/25 p-4 text-sm leading-6 text-black/60"><b>Fair-work check:</b> task payment must be clear, work must fit the stated time, and sensitive account access is prohibited.</div><button className="w-full rounded-2xl bg-ink px-5 py-4 font-black text-white">Publish task</button></form></section>}
    {view==="reviews"&&<section><Pill>Business verification</Pill><h1 className="mt-4 text-4xl font-black">Review completed work.</h1><div className="mt-8 space-y-4">{data.tasks.filter(t=>t.status==="submitted").map(t=><article key={t.id} className="rounded-[2rem] bg-white p-6"><div className="flex flex-col justify-between gap-4 sm:flex-row"><div><h2 className="text-2xl font-black">{t.title}</h2><p className="mt-1 text-black/50">Submitted by {t.worker}</p></div><span className="self-start rounded-full bg-sun/40 px-3 py-1 text-xs font-black">Awaiting verification</span></div><div className="mt-5 rounded-2xl bg-sand p-4"><p className="text-xs font-black uppercase tracking-wider text-black/40">Worker summary</p><p className="mt-2 leading-7">{t.submission}</p></div><div className="mt-5 flex flex-col gap-3 sm:flex-row"><button onClick={()=>verifyTask(t.id)} className="rounded-2xl bg-forest px-5 py-3 font-black text-white">Verify and release R{t.pay}</button><button className="rounded-2xl border border-black/10 px-5 py-3 font-black">Request correction</button></div></article>)}{!data.tasks.some(t=>t.status==="submitted")&&<Empty title="No submissions waiting" body="Completed worker submissions will appear here for verification."/>}</div></section>}
    {view==="admin"&&<section><Pill>Trust and safety</Pill><h1 className="mt-4 text-4xl font-black">Nala operations centre</h1><div className="mt-8 grid gap-4 sm:grid-cols-3"><Metric icon={ShieldCheck} label="Open safety reports" value="0"/><Metric icon={Clock3} label="Tasks awaiting review" value={String(data.tasks.filter(t=>t.status==="submitted").length)}/><Metric icon={Building2} label="Active businesses" value="4"/></div><div className="mt-8 rounded-[2rem] bg-white p-6"><h2 className="text-2xl font-black">Marketplace checks</h2><div className="mt-5 space-y-3">{["No unpaid trial tasks detected","All open tasks display payment","No banking-access tasks detected","Customer data stays inside scoped work"].map(x=><div key={x} className="flex items-center gap-3 rounded-2xl bg-leaf/20 p-4"><Check className="text-forest"/><span className="font-bold">{x}</span></div>)}</div></div></section>}
   </main>
  </div>
 </div>
}
