"use client";

import Link from "next/link";
import {useEffect,useMemo,useState} from "react";
import {ArrowLeft,ArrowRight,BadgeCheck,BriefcaseBusiness,Check,ChevronRight,CircleDollarSign,ClipboardCheck,FileCheck2,Home,LayoutDashboard,Menu,Plus,RotateCcw,ShieldCheck,Sparkles,Star,Trash2,X} from "lucide-react";

export type WorkspaceRole="worker"|"business"|"admin";
export type WorkspaceView="dashboard"|"market"|"task"|"workbench"|"passport"|"create"|"reviews"|"operations";
type TaskStatus="open"|"accepted"|"submitted"|"changes_requested"|"verified";
type Task={id:string;title:string;business:string;category:string;pay:number;duration:string;description:string;skills:string[];status:TaskStatus;worker?:string;submission?:string;feedback?:string;rating?:number};
type State={mode:"empty"|"demo"|"custom";workerName:string;businessName:string;earnings:number;verified:number;reliability:number;tasks:Task[]};

const STORAGE_KEY="nala-sandbox-state-v2";
const EMPTY_STATE:State={mode:"empty",workerName:"New worker",businessName:"Your business",earnings:0,verified:0,reliability:0,tasks:[]};
const DEMO_STATE:State={mode:"demo",workerName:"Thandi Mokoena",businessName:"Lerato Beauty Studio",earnings:270,verified:2,reliability:96,tasks:[
 {id:"appointment-confirmation",title:"Confirm tomorrow’s appointments",business:"Lerato Beauty Studio",category:"Customer support",pay:100,duration:"45–60 min",description:"Contact 10 customers using the approved message, record responses and flag anything the owner must handle.",skills:["Customer communication","Accuracy","WhatsApp admin"],status:"open"},
 {id:"quote-follow-up",title:"Prepare quote follow-up messages",business:"Mandla Electrical",category:"Sales administration",pay:150,duration:"60–90 min",description:"Prepare professional follow-up messages for eight customers who received quotations this month.",skills:["Professional writing","Sales support","Attention to detail"],status:"accepted",worker:"Thandi Mokoena"},
 {id:"salon-review",title:"Update the cancelled-booking list",business:"Lerato Beauty Studio",category:"Data administration",pay:90,duration:"35–45 min",description:"Review the supplied booking list, mark cancellations and return a clean summary for the salon owner.",skills:["Data accuracy","Admin organisation"],status:"submitted",worker:"Thandi Mokoena",submission:"Reviewed 18 bookings, marked 3 cancellations, corrected 2 phone numbers and flagged one duplicate customer record."},
 {id:"completed-1",title:"Clean customer contact spreadsheet",business:"Naledi Repairs",category:"Data administration",pay:120,duration:"1 hour",description:"Standardise phone numbers and remove duplicates.",skills:["Spreadsheet cleanup","Data accuracy"],status:"verified",worker:"Thandi Mokoena",rating:5,submission:"Cleaned the contact list, standardised 84 phone numbers and removed 11 duplicates."},
 {id:"completed-2",title:"Prepare customer follow-up list",business:"Lerato Beauty Studio",category:"Customer support",pay:150,duration:"75 min",description:"Organise follow-up contacts and prepare approved messages.",skills:["Customer communication","Admin accuracy"],status:"verified",worker:"Thandi Mokoena",rating:5,submission:"Prepared 12 follow-up records and highlighted two customers needing owner attention."}
]};
const steps=["Review the approved customer list","Use the approved confirmation message","Record every customer response","Flag questions for the business owner","Complete the final quality check"];

function clone<T>(value:T):T{return JSON.parse(JSON.stringify(value));}
function usePersistentState(){
 const [data,setData]=useState<State>(EMPTY_STATE);const [ready,setReady]=useState(false);
 useEffect(()=>{try{const raw=localStorage.getItem(STORAGE_KEY);if(raw)setData(JSON.parse(raw))}catch{localStorage.removeItem(STORAGE_KEY)}finally{setReady(true)}},[]);
 useEffect(()=>{if(ready)localStorage.setItem(STORAGE_KEY,JSON.stringify(data))},[data,ready]);
 return {data,setData,ready};
}
function Header({eyebrow,title,copy}:{eyebrow:string;title:string;copy:string}){return <><div className="page-eyebrow">{eyebrow}</div><h1 className="page-title">{title}</h1><p className="page-copy">{copy}</p></>}
function Metric({icon:Icon,label,value}:{icon:any;label:string;value:string}){return <div className="metric-card"><Icon size={20}/><strong>{value}</strong><span>{label}</span></div>}
function Empty({title,body}:{title:string;body:string}){return <div className="empty-state"><Sparkles className="mx-auto"/><strong className="mt-3 block text-lg text-ink">{title}</strong><p className="mt-2 text-sm">{body}</p></div>}

export function ProductionApp({role,initialView="dashboard"}:{role:WorkspaceRole;initialView?:WorkspaceView}){
 const {data,setData,ready}=usePersistentState();
 const [view,setView]=useState<WorkspaceView>(role==="admin"?"operations":initialView);const [selected,setSelected]=useState("");const [menu,setMenu]=useState(false);const [practice,setPractice]=useState(false);const [checked,setChecked]=useState<number[]>([]);const [submission,setSubmission]=useState("");const [feedback,setFeedback]=useState("");const [controls,setControls]=useState(false);
 const task=data.tasks.find(t=>t.id===selected)||data.tasks[0];
 const open=data.tasks.filter(t=>t.status==="open");const active=data.tasks.filter(t=>["accepted","submitted","changes_requested"].includes(t.status));const verified=data.tasks.filter(t=>t.status==="verified");const submitted=data.tasks.filter(t=>t.status==="submitted");const businessTasks=data.tasks.filter(t=>t.business===data.businessName);
 const nav=useMemo(()=>role==="worker"?[["dashboard","My progress",Home],["market","Find work",BriefcaseBusiness],["workbench","My work",ClipboardCheck],["passport","Work passport",BadgeCheck]]:role==="business"?[["dashboard","Overview",LayoutDashboard],["create","Create task",Plus],["market","Task board",BriefcaseBusiness],["reviews","Review work",FileCheck2]]:[["operations","Marketplace health",ShieldCheck],["market","All tasks",BriefcaseBusiness],["reviews","Review queue",FileCheck2]],[role]);
 function loadDemo(){setData(clone(DEMO_STATE));setSelected("appointment-confirmation");setChecked([]);setSubmission("");setFeedback("");setPractice(false);setView(role==="admin"?"operations":"dashboard");setControls(false)}
 function resetDemo(){if(!confirm("Reset all demo changes and restore the original Nala scenario?"))return;loadDemo()}
 function clearDemo(){if(!confirm("Clear all local sandbox data on this device?"))return;setData(clone(EMPTY_STATE));setSelected("");setChecked([]);setSubmission("");setFeedback("");setPractice(false);setView(role==="admin"?"operations":"dashboard");setControls(false)}
 function markCustom(next:State):State{return {...next,mode:next.mode==="empty"?"custom":next.mode}}
 function openTask(id:string){setSelected(id);setView("task")}
 function accept(){if(!task)return;setData(d=>markCustom({...d,tasks:d.tasks.map(t=>t.id===task.id?{...t,status:"accepted",worker:d.workerName,feedback:undefined}:t)}));setPractice(false);setChecked([]);setView("workbench")}
 function submit(){if(!task||checked.length!==steps.length||submission.trim().length<20)return;setData(d=>markCustom({...d,tasks:d.tasks.map(t=>t.id===task.id?{...t,status:"submitted",submission:submission.trim(),feedback:undefined}:t)}));setSubmission("");setChecked([]);setView("dashboard")}
 function verify(id:string){const target=data.tasks.find(t=>t.id===id);if(!target||target.status!=="submitted")return;setData(d=>markCustom({...d,earnings:d.earnings+target.pay,verified:d.verified+1,reliability:Math.min(100,d.reliability+1),tasks:d.tasks.map(t=>t.id===id?{...t,status:"verified",rating:5,feedback:undefined}:t)}));setView("dashboard")}
 function requestChanges(id:string){if(feedback.trim().length<10)return;setData(d=>markCustom({...d,tasks:d.tasks.map(t=>t.id===id?{...t,status:"changes_requested",feedback:feedback.trim()}:t)}));setFeedback("");setView("dashboard")}
 function createTask(e:React.FormEvent<HTMLFormElement>){e.preventDefault();const f=new FormData(e.currentTarget);const pay=Number(f.get("pay"));const title=String(f.get("title")||"").trim();const description=String(f.get("description")||"").trim();if(title.length<8||description.length<20||!Number.isFinite(pay)||pay<50)return;const next:Task={id:`task-${Date.now()}`,title,business:data.businessName==="Your business"?"Your business":data.businessName,category:String(f.get("category")),pay,duration:String(f.get("duration")).trim(),description,skills:String(f.get("skills")).split(",").map(s=>s.trim()).filter(Boolean),status:"open"};setData(d=>markCustom({...d,tasks:[next,...d.tasks]}));setSelected(next.id);e.currentTarget.reset();setView("task")}
 if(!ready)return <main className="grid min-h-screen place-items-center bg-sand"><p className="font-bold">Opening Nala…</p></main>;
 return <div className={`app-shell workspace-role-${role}`}>
  <header className="app-topbar"><Link href="/" className="app-brand">nala<span>.</span></Link><div className="flex items-center gap-3"><span className={`status-chip ${data.mode==="demo"?"":"opacity-70"}`}>{data.mode==="demo"?"Demo mode":data.mode==="empty"?"Empty workspace":"Local sandbox"}</span><button className="outline-button !py-2" onClick={()=>setControls(!controls)}>Demo controls</button></div><button className="mobile-menu" onClick={()=>setMenu(!menu)} aria-label="Toggle navigation">{menu?<X/>:<Menu/>}</button></header>
  {controls&&<div className="mx-auto mt-4 max-w-[1376px] px-5"><section className="rounded-[20px] border border-line bg-white p-5 shadow-sm"><div className="flex flex-col justify-between gap-4 md:flex-row md:items-center"><div><strong className="text-lg">Nala sandbox controls</strong><p className="mt-1 text-sm text-black/55">Load a realistic {role} scenario, reset it after testing, or return to a clean first-time workspace. Changes stay on this device and are never treated as live marketplace records.</p></div><div className="flex flex-wrap gap-2"><button className="solid-button" onClick={loadDemo}><Sparkles size={16}/>Load {role} demo</button><button className="outline-button" onClick={resetDemo} disabled={data.mode!=="demo"}><RotateCcw size={16}/>Reset demo</button><button className="outline-button" onClick={clearDemo}><Trash2 size={16}/>Clear data</button></div></div></section></div>}
  <div className="app-layout"><aside className={`app-sidebar ${menu?"!block":""}`}><div className="persona-card"><small>{role==="worker"?"WORKER PROFILE":role==="business"?"BUSINESS ACCOUNT":"OPERATIONS ACCOUNT"}</small><strong>{role==="worker"?data.workerName:role==="business"?data.businessName:"Nala Trust & Safety"}</strong><p>{data.mode==="demo"?"Sandbox scenario loaded":data.mode==="empty"?"No local records yet":"Local sandbox activity"}</p></div><nav className="side-nav">{nav.map(([id,label,Icon]:any)=><button key={id} className={view===id?"active":""} onClick={()=>{setView(id);setMenu(false)}}><Icon size={18}/>{label}</button>)}</nav><div className="sidebar-note">{data.mode==="demo"?"Demo records are isolated, resettable and stored only on this device.":role==="worker"?"Every task shows payment, scope and proof requirements before acceptance.":role==="business"?"Create clear outcomes and review delivered work before approval.":"Protect fair work, business trust and worker dignity."}</div></aside>
  <main className="app-main"><div className="app-page">
   {view==="dashboard"&&role==="worker"&&<><Header eyebrow="Your work journey" title={data.mode==="empty"?"Your first work journey starts here.":`Good to see you, ${data.workerName.split(" ")[0]}.`} copy={data.mode==="empty"?"Load the worker demo to explore a complete journey, or wait for real account onboarding when Supabase is connected.":"Every verified task adds trusted evidence to your work history."}/><div className="metric-grid"><Metric icon={CircleDollarSign} label="Verified earnings" value={`R${data.earnings}`}/><Metric icon={BadgeCheck} label="Verified tasks" value={String(data.verified)}/><Metric icon={Star} label="Reliability" value={`${data.reliability}%`}/></div><section className="panel mt-[18px]"><div className="section-actions"><div><h2>Your current work</h2><p className="panel-sub">Accepted work, submissions, and requested corrections.</p></div><button className="solid-button" onClick={()=>setView("market")}>Find work <ArrowRight size={16}/></button></div><div className="task-list">{active.length?active.map(t=><button className="task-row" key={t.id} onClick={()=>{setSelected(t.id);setView("workbench")}}><div><strong>{t.title}</strong><p>{t.business} · {t.status.replace("_"," ")}{t.feedback?` · ${t.feedback}`:""}</p></div><ChevronRight/></button>):<Empty title="No work in progress" body={data.mode==="empty"?"Use Demo controls to load a realistic worker journey.":"Choose a suitable starter task when you are ready."}/>}</div></section></>}
   {view==="dashboard"&&role==="business"&&<><Header eyebrow="Business workspace" title={data.mode==="empty"?"Create work that moves your business forward.":"Keep important work moving."} copy={data.mode==="empty"?"Load the business demo to inspect publishing, submissions and verification, or begin with a clean local task board.":"Create clear outcomes, review submissions, and approve only work that meets the brief."}/><div className="metric-grid"><Metric icon={BriefcaseBusiness} label="Tasks created" value={String(businessTasks.length)}/><Metric icon={CircleDollarSign} label="Task value" value={`R${businessTasks.reduce((s,t)=>s+t.pay,0)}`}/><Metric icon={FileCheck2} label="Waiting for review" value={String(submitted.filter(t=>t.business===data.businessName).length)}/></div><section className="panel mt-[18px]"><div className="section-actions"><div><h2>Work needing attention</h2><p className="panel-sub">Worker submissions waiting for your decision.</p></div><button className="solid-button" onClick={()=>setView("create")}><Plus size={16}/>Create task</button></div><div className="task-list">{submitted.filter(t=>t.business===data.businessName).length?submitted.filter(t=>t.business===data.businessName).map(t=><button className="task-row" key={t.id} onClick={()=>setView("reviews")}><div><strong>{t.title}</strong><p>{t.worker} submitted work</p></div><span className="status-chip">Review</span></button>):<Empty title="No reviews waiting" body={data.mode==="empty"?"Load the business demo to see a realistic review queue.":"Submitted work will appear here."}/>}</div></section></>}
   {view==="operations"&&<><Header eyebrow="Trust & safety" title="Marketplace health." copy="The live backend will power cross-account moderation. This sandbox validates task lifecycle and fair-work rules."/><div className="metric-grid"><Metric icon={ShieldCheck} label="Safety flags" value="0"/><Metric icon={BriefcaseBusiness} label="Open tasks" value={String(open.length)}/><Metric icon={ClipboardCheck} label="Active assignments" value={String(active.length)}/></div></>}
   {view==="market"&&<><Header eyebrow={role==="worker"?"Matched starter work":"Task board"} title={role==="worker"?"Work you can succeed at.":"Clear work. Visible status."} copy={role==="worker"?"Review payment, time, scope and skills before accepting.":"Inspect tasks and their current delivery state."}/>{(role==="worker"?open:role==="business"?businessTasks:data.tasks).length?<div className="market-grid">{(role==="worker"?open:role==="business"?businessTasks:data.tasks).map(t=><button className="market-card" key={t.id} onClick={()=>openTask(t.id)}><div className="market-card-top"><span className="status-chip">{t.status.replace("_"," ")}</span><strong className="text-2xl">R{t.pay}</strong></div><h3>{t.title}</h3><p>{t.business} · {t.duration}</p><p>{t.description}</p><div className="skill-row">{t.skills.map(s=><span key={s}>{s}</span>)}</div></button>)}</div>:<Empty title="No tasks yet" body="Load a demo scenario or create the first local task."/>}</>}
   {view==="task"&&task&&<section className="detail-card"><button className="mb-5 flex items-center gap-2 text-sm font-bold text-forest" onClick={()=>setView("market")}><ArrowLeft size={16}/>Back</button><div className="detail-head"><div><div className="page-eyebrow">{task.category}</div><h1 className="page-title !text-[44px]">{task.title}</h1><p className="page-copy">{task.business}</p></div><div className="detail-pay"><small>{role==="worker"?"YOU EARN":"TASK VALUE"}</small><strong>R{task.pay}</strong><span className="block text-xs">{task.duration}</span></div></div><div className="mt-7"><h2 className="text-xl font-black">What needs to be done</h2><p className="mt-3 leading-7 text-black/60">{task.description}</p><div className="skill-row">{task.skills.map(s=><span key={s}>{s}</span>)}</div></div>{role==="worker"&&task.status==="open"&&<div className="mt-8 rounded-[20px] border border-line bg-sand p-5">{!practice?<><strong>Readiness check required</strong><p className="mt-2 text-sm">Practise the expected professional tone before accepting work.</p><button className="solid-button mt-4" onClick={()=>setPractice(true)}>Start readiness check</button></>:<><strong>Choose the professional approach</strong><p className="mt-3 rounded-xl bg-white p-4 text-sm">“Hi Naledi, are you still able to attend tomorrow at 10:00? Please reply YES to confirm or let us know if you need to reschedule.”</p><button className="solid-button mt-4" onClick={accept}><Check size={16}/>Accept task and open workbench</button></>}</div>}</section>}
   {view==="workbench"&&<><Header eyebrow="Guided workbench" title={task?.title||"My work"} copy="Complete every step and provide a clear result summary."/>{!active.length?<Empty title="Nothing in progress" body="Accept a task from Find work first."/>:<div className="content-grid"><section className="panel"><div className="checklist">{steps.map((s,i)=><div className={`check-item ${checked.includes(i)?"done":""}`} key={s}><button onClick={()=>setChecked(c=>c.includes(i)?c.filter(x=>x!==i):[...c,i])}>{checked.includes(i)&&<Check size={15}/>}</button><strong>{s}</strong></div>)}</div>{task?.feedback&&<div className="mt-5 rounded-xl bg-sand p-4"><strong>Correction requested</strong><p className="mt-2 text-sm">{task.feedback}</p></div>}</section><aside className="panel"><h2>Submit your result</h2><div className="field mt-5"><textarea value={submission} onChange={e=>setSubmission(e.target.value)} placeholder="Describe what you completed and any issue the owner must know (minimum 20 characters)."/></div><button className="solid-button mt-4 w-full" disabled={checked.length!==steps.length||submission.trim().length<20} onClick={submit}>Submit for review</button></aside></div>}</>}
   {view==="passport"&&<><Header eyebrow="Verified proof of work" title={`${data.workerName}’s work passport`} copy="Only business-approved work appears here."/><div className="metric-grid"><Metric icon={BadgeCheck} label="Verified tasks" value={String(data.verified)}/><Metric icon={Star} label="Reliability" value={`${data.reliability}%`}/><Metric icon={CircleDollarSign} label="Verified earnings" value={`R${data.earnings}`}/></div><section className="panel mt-[18px]"><div className="task-list">{verified.length?verified.map(t=><article className="review-card" key={t.id}><span className="status-chip">Verified</span><h3 className="mt-3 text-xl font-black">{t.title}</h3><p className="mt-1 text-sm text-forest">{t.business}</p><p className="mt-4 text-sm">{t.submission}</p><div className="skill-row">{t.skills.map(s=><span key={s}>{s}</span>)}</div></article>):<Empty title="No verified work yet" body="Verified tasks will build this passport."/>}</div></section></>}
   {view==="create"&&<><Header eyebrow="Create a structured outcome" title="What important work needs to move?" copy="Publish only clear, safe work with visible payment and a defined result."/><form className="panel mt-7" onSubmit={createTask}><div className="form-grid"><div className="field full"><label>TASK TITLE</label><input name="title" minLength={8} required/></div><div className="field"><label>CATEGORY</label><select name="category"><option>Customer support</option><option>Sales administration</option><option>Data administration</option><option>Digital marketing</option></select></div><div className="field"><label>PAYMENT (R)</label><input name="pay" type="number" min="50" required/></div><div className="field"><label>ESTIMATED TIME</label><input name="duration" required/></div><div className="field"><label>SKILLS</label><input name="skills" required/></div><div className="field full"><label>WHAT MUST BE COMPLETED?</label><textarea name="description" minLength={20} required/></div></div><button className="solid-button mt-5" type="submit">Create and publish task</button></form></>}
   {view==="reviews"&&<><Header eyebrow={role==="admin"?"Review oversight":"Business review"} title={role==="admin"?"Submission queue":"Approve work that meets the brief."} copy="Review the worker summary and make a real decision."/><div className="mt-7">{submitted.filter(t=>role!=="business"||t.business===data.businessName).length?submitted.filter(t=>role!=="business"||t.business===data.businessName).map(t=><article className="review-card" key={t.id}><span className="status-chip">Submitted</span><h2 className="mt-3 text-2xl font-black">{t.title}</h2><p className="mt-4 rounded-[16px] bg-sand p-4">{t.submission}</p>{role==="business"&&<><div className="field mt-4"><textarea value={feedback} onChange={e=>setFeedback(e.target.value)} placeholder="Correction reason (required only when returning work)"/></div><div className="mt-4 flex flex-wrap gap-3"><button className="solid-button" onClick={()=>verify(t.id)}>Verify and approve</button><button className="outline-button" disabled={feedback.trim().length<10} onClick={()=>requestChanges(t.id)}>Request correction</button></div></>}</article>):<Empty title="Nothing waiting" body={data.mode==="empty"?"Load the business demo to inspect a complete review flow.":"New submissions will appear here."}/>}</div></>}
  </div></main></div></div>;
}
