-- Applied to Supabase project cvmycngyaaqfyfeaaszh on 2026-07-15.
-- This migration is retained in source control as the production schema contract.
create extension if not exists pgcrypto;

do $$ begin create type public.market_cell_status as enum ('planning','pilot','controlled_growth','paused','healthy'); exception when duplicate_object then null; end $$;
do $$ begin create type public.task_product_status as enum ('draft','pilot','available','paused','retired'); exception when duplicate_object then null; end $$;
do $$ begin create type public.task_request_status as enum ('draft','needs_review','approved','funding_pending','funded','published','allocated','completed','cancelled'); exception when duplicate_object then null; end $$;
do $$ begin create type public.waitlist_status as enum ('waiting','invited','activated','closed'); exception when duplicate_object then null; end $$;
do $$ begin create type public.recurrence_cadence as enum ('once','weekly','fortnightly','monthly','service_cycle'); exception when duplicate_object then null; end $$;

create table if not exists public.market_cells(id uuid primary key default gen_random_uuid(),slug text not null unique,name text not null,geography text not null,verticals text[] not null default '{}',status public.market_cell_status not null default 'planning',worker_capacity integer not null default 0 check(worker_capacity>=0),active_worker_count integer not null default 0 check(active_worker_count>=0),funded_open_task_count integer not null default 0 check(funded_open_task_count>=0),target_monthly_tasks integer not null default 0 check(target_monthly_tasks>=0),last_reviewed_at timestamptz,created_at timestamptz not null default now(),updated_at timestamptz not null default now());
create table if not exists public.task_products(id uuid primary key default gen_random_uuid(),slug text not null unique,title text not null,category text not null,verticals text[] not null default '{}',status public.task_product_status not null default 'draft',outcome text not null,source_inputs text[] not null default '{}',completion_checklist text[] not null default '{}',evidence_requirements text[] not null default '{}',prohibited_information text[] not null default '{}',review_rubric jsonb not null default '{}'::jsonb,readiness_simulation_id text,expected_active_minutes integer not null check(expected_active_minutes>0),expected_revision_minutes integer not null default 0 check(expected_revision_minutes>=0),minimum_worker_pay_cents integer not null check(minimum_worker_pay_cents>=0),revision_limit integer not null default 1 check(revision_limit between 0 and 3),remote_capable boolean not null default true,created_at timestamptz not null default now(),updated_at timestamptz not null default now());
create table if not exists public.business_profiles(id uuid primary key default gen_random_uuid(),owner_user_id uuid references auth.users(id) on delete cascade,market_cell_id uuid references public.market_cells(id) on delete set null,name text not null,vertical text not null,verification_status text not null default 'pending' check(verification_status in ('pending','verified','restricted','rejected')),payment_readiness_status text not null default 'not_ready' check(payment_readiness_status in ('not_ready','pending','ready','restricted')),successful_task_count integer not null default 0,repeat_task_count integer not null default 0,created_at timestamptz not null default now(),updated_at timestamptz not null default now());
create table if not exists public.worker_profiles(id uuid primary key default gen_random_uuid(),owner_user_id uuid references auth.users(id) on delete cascade,market_cell_id uuid references public.market_cells(id) on delete set null,display_name text not null,geography text,interested_categories text[] not null default '{}',ready_categories text[] not null default '{}',active boolean not null default true,created_at timestamptz not null default now(),updated_at timestamptz not null default now());
create table if not exists public.waitlist_entries(id uuid primary key default gen_random_uuid(),worker_profile_id uuid references public.worker_profiles(id) on delete cascade,market_cell_id uuid not null references public.market_cells(id) on delete cascade,category text not null,status public.waitlist_status not null default 'waiting',joined_at timestamptz not null default now(),invited_at timestamptz,unique(worker_profile_id,market_cell_id,category));
create table if not exists public.task_requests(id uuid primary key default gen_random_uuid(),business_profile_id uuid not null references public.business_profiles(id) on delete cascade,market_cell_id uuid not null references public.market_cells(id) on delete restrict,task_product_id uuid not null references public.task_products(id) on delete restrict,status public.task_request_status not null default 'draft',cadence public.recurrence_cadence not null default 'once',worker_pay_cents integer not null check(worker_pay_cents>=0),service_fee_cents integer not null default 0 check(service_fee_cents>=0),funding_reference text,funded_at timestamptz,published_at timestamptz,due_at timestamptz,source_payload jsonb not null default '{}'::jsonb,created_at timestamptz not null default now(),updated_at timestamptz not null default now(),constraint no_unfunded_publication check(status not in ('funded','published','allocated','completed') or funded_at is not null));
create table if not exists public.recurring_task_plans(id uuid primary key default gen_random_uuid(),business_profile_id uuid not null references public.business_profiles(id) on delete cascade,task_product_id uuid not null references public.task_products(id) on delete restrict,market_cell_id uuid not null references public.market_cells(id) on delete restrict,cadence public.recurrence_cadence not null,active boolean not null default true,next_run_at timestamptz,worker_pay_cents integer not null check(worker_pay_cents>=0),preferred_worker_profile_id uuid references public.worker_profiles(id) on delete set null,created_at timestamptz not null default now(),updated_at timestamptz not null default now());
create table if not exists public.preferred_worker_relationships(id uuid primary key default gen_random_uuid(),business_profile_id uuid not null references public.business_profiles(id) on delete cascade,worker_profile_id uuid not null references public.worker_profiles(id) on delete cascade,task_product_id uuid references public.task_products(id) on delete set null,status text not null default 'preferred' check(status in ('preferred','paused','blocked')),successful_task_count integer not null default 0,last_completed_at timestamptz,created_at timestamptz not null default now(),unique(business_profile_id,worker_profile_id,task_product_id));
create table if not exists public.analytics_events(id bigint generated always as identity primary key,occurred_at timestamptz not null default now(),actor_user_id uuid references auth.users(id) on delete set null,market_cell_id uuid references public.market_cells(id) on delete set null,event_name text not null,entity_type text,entity_id text,properties jsonb not null default '{}'::jsonb);

create or replace function public.touch_updated_at() returns trigger language plpgsql as $$begin new.updated_at=now();return new;end$$;
create or replace view public.market_health_public with(security_invoker=true) as select mc.id,mc.slug,mc.name,mc.geography,mc.verticals,mc.status,mc.worker_capacity,mc.active_worker_count,mc.funded_open_task_count,case when mc.active_worker_count=0 then null else round(mc.funded_open_task_count::numeric/mc.active_worker_count,2) end funded_tasks_per_active_worker,case when mc.active_worker_count=0 then 'building_supply' when mc.funded_open_task_count::numeric/mc.active_worker_count<0.15 then 'severe_worker_oversupply' when mc.funded_open_task_count::numeric/mc.active_worker_count<0.35 then 'thin_demand' when mc.funded_open_task_count::numeric/mc.active_worker_count<0.75 then 'developing' when mc.funded_open_task_count::numeric/mc.active_worker_count<=1.5 then 'healthy' else 'worker_shortage' end health_band,mc.last_reviewed_at from public.market_cells mc;

alter table public.market_cells enable row level security; alter table public.task_products enable row level security; alter table public.business_profiles enable row level security; alter table public.worker_profiles enable row level security; alter table public.waitlist_entries enable row level security; alter table public.task_requests enable row level security; alter table public.recurring_task_plans enable row level security; alter table public.preferred_worker_relationships enable row level security; alter table public.analytics_events enable row level security;

do $$ begin create policy "public can read active market cells" on public.market_cells for select to anon,authenticated using(status in ('pilot','controlled_growth','healthy')); exception when duplicate_object then null; end $$;
do $$ begin create policy "public can read available task products" on public.task_products for select to anon,authenticated using(status in ('pilot','available')); exception when duplicate_object then null; end $$;
do $$ begin create policy "users manage own worker profile" on public.worker_profiles for all to authenticated using(owner_user_id=auth.uid()) with check(owner_user_id=auth.uid()); exception when duplicate_object then null; end $$;
do $$ begin create policy "users manage own business profile" on public.business_profiles for all to authenticated using(owner_user_id=auth.uid()) with check(owner_user_id=auth.uid()); exception when duplicate_object then null; end $$;

grant select on public.market_cells,public.task_products,public.market_health_public to anon,authenticated;
grant select,insert,update,delete on public.business_profiles,public.worker_profiles,public.waitlist_entries,public.task_requests,public.recurring_task_plans to authenticated;
grant select on public.preferred_worker_relationships to authenticated; grant insert on public.analytics_events to authenticated;
