-- Applied to Supabase project cvmycngyaaqfyfeaaszh on 2026-07-15.
-- Distribution operations: partner cohorts, structured intake, market reviews and trust/safety cases.
create table if not exists public.partner_cohorts(id uuid primary key default gen_random_uuid(),name text not null,partner_type text not null check(partner_type in('worker_distribution','business_distribution','sponsor','training','municipal','other')),geography text not null,market_cell_id uuid references public.market_cells(id) on delete set null,status text not null default 'planning' check(status in('planning','active','paused','completed')),worker_target integer not null default 0 check(worker_target>=0),business_target integer not null default 0 check(business_target>=0),funded_task_target integer not null default 0 check(funded_task_target>=0),starts_at timestamptz,ends_at timestamptz,created_at timestamptz not null default now(),updated_at timestamptz not null default now());
create table if not exists public.business_intake_requests(id uuid primary key default gen_random_uuid(),source text not null default 'web' check(source in('web','whatsapp','partner','operator')),contact_name text not null,business_name text not null,contact_phone text,contact_email text,geography text,vertical text,requested_outcome text not null,preferred_task_product_slug text,urgency text not null default 'standard' check(urgency in('standard','urgent')),consent_to_contact boolean not null default false,status text not null default 'new' check(status in('new','triaged','needs_information','approved','declined','converted')),safety_flags text[] not null default '{}',operator_notes text,created_at timestamptz not null default now(),updated_at timestamptz not null default now());
create table if not exists public.market_reviews(id uuid primary key default gen_random_uuid(),market_cell_id uuid not null references public.market_cells(id) on delete cascade,reviewed_at timestamptz not null default now(),funded_tasks integer not null default 0 check(funded_tasks>=0),ready_workers integer not null default 0 check(ready_workers>=0),active_businesses integer not null default 0 check(active_businesses>=0),matched_task_rate numeric(5,2),first_pass_approval_rate numeric(5,2),repeat_business_rate numeric(5,2),dispute_rate numeric(5,2),median_worker_pay_cents integer,operator_summary text,created_at timestamptz not null default now());
create table if not exists public.trust_safety_cases(id uuid primary key default gen_random_uuid(),case_type text not null check(case_type in('unsafe_task','payment_delay','data_risk','harassment','off_platform_pressure','dispute','fraud','other')),status text not null default 'open' check(status in('open','investigating','resolved','dismissed')),severity text not null default 'medium' check(severity in('low','medium','high','critical')),business_profile_id uuid references public.business_profiles(id) on delete set null,worker_profile_id uuid references public.worker_profiles(id) on delete set null,task_request_id uuid references public.task_requests(id) on delete set null,summary text not null,resolution text,created_at timestamptz not null default now(),resolved_at timestamptz);
alter table public.partner_cohorts enable row level security;alter table public.business_intake_requests enable row level security;alter table public.market_reviews enable row level security;alter table public.trust_safety_cases enable row level security;
do $$ begin create policy "public can submit consented business intake" on public.business_intake_requests for insert to anon,authenticated with check(consent_to_contact=true and length(trim(requested_outcome))>=10 and length(trim(contact_name))>=2 and length(trim(business_name))>=2); exception when duplicate_object then null; end $$;
do $$ begin create policy "public can read active partner cohorts" on public.partner_cohorts for select to anon,authenticated using(status='active'); exception when duplicate_object then null; end $$;
do $$ begin create policy "public can read market reviews" on public.market_reviews for select to anon,authenticated using(true); exception when duplicate_object then null; end $$;
grant insert on public.business_intake_requests to anon,authenticated;grant select on public.partner_cohorts,public.market_reviews to anon,authenticated;
create or replace view public.distribution_readiness_public with(security_invoker=true) as select mc.id market_cell_id,mc.name market_cell_name,mc.geography,mc.status,mc.worker_capacity,mc.active_worker_count,mc.funded_open_task_count,coalesce((select count(*) from public.task_products tp where tp.status in('pilot','available') and tp.verticals&&mc.verticals),0) active_task_products,coalesce((select count(*) from public.partner_cohorts pc where pc.market_cell_id=mc.id and pc.status='active'),0) active_partner_cohorts,coalesce((select count(*) from public.business_profiles bp where bp.market_cell_id=mc.id and bp.verification_status='verified'),0) verified_businesses,coalesce((select count(*) from public.recurring_task_plans rp where rp.market_cell_id=mc.id and rp.active),0) recurring_plans,coalesce((select max(mr.reviewed_at) from public.market_reviews mr where mr.market_cell_id=mc.id),mc.last_reviewed_at) last_reviewed_at from public.market_cells mc;
grant select on public.distribution_readiness_public to anon,authenticated;
